import { BadRequestException, Injectable } from '@nestjs/common';
import { SystemPrismaService } from './prisma.service.js';

/**
 * Whitelist of DB operations that genuinely cannot be tenant-scoped.
 *
 * There are only two such operations in the MVP, both at the auth boundary:
 *
 *   1. `findUserByEmail` — at login, we don't know the tenant yet.
 *   2. `findFreshMagicLinks` — we receive a raw token and must find the row
 *       before we know the tenant.
 *
 * Anything else MUST go through `TenantDb` (see ./with-tenant.ts).
 *
 * These queries run as the migration role (superuser) because `rhud_app` is
 * NOBYPASSRLS and can't read these tables without an app.tenant_id set. That
 * asymmetry is deliberate: unscoped access requires an explicit addition to
 * this file, visible in code review.
 */
@Injectable()
export class UnscopedDb {
  constructor(private readonly prisma: SystemPrismaService) {}

  async findUserByEmail(email: string): Promise<{
    id: string;
    tenantId: string;
    email: string;
    role: string;
    passwordHash: string | null;
    emailVerified: boolean;
  } | null> {
    const rows = await this.prisma.$queryRaw<
      Array<{
        id: string;
        tenant_id: string;
        email: string;
        role: string;
        password_hash: string | null;
        email_verified: boolean;
      }>
    >`SELECT id, tenant_id, email, role, password_hash, email_verified
        FROM users
       WHERE email = ${email}::citext
       LIMIT 1`;
    const r = rows[0];
    if (!r) return null;
    return {
      id: r.id,
      tenantId: r.tenant_id,
      email: r.email,
      role: r.role,
      passwordHash: r.password_hash,
      emailVerified: r.email_verified,
    };
  }

  /**
   * Atomic create of a brand-new tenant + admin user for self-serve signup.
   * Runs as the migration role (superuser) because the new tenant doesn't
   * exist yet, so there's no `app.tenant_id` we could set first.
   *
   * Returns the inserted user's id + tenant id so the caller can email the
   * verification link (the token hash is written here; the plaintext is
   * generated by the caller and is what the email contains).
   */
  async createTenantWithAdmin(args: {
    tenantName: string;
    email: string;
    /** Optional human display name the user typed during signup. Persisted
     *  to `users.name` so the dashboard can greet them properly. */
    userName?: string;
    /** Industry-template slug to clone the starting taxonomy from.
     *  Defaults to 'cybersecurity' (matches the column default + back-compat).
     *  Validated inside the transaction; an unknown slug rolls everything
     *  back so we never half-create a tenant. */
    industryTemplateSlug?: string;
    passwordHash: string;
    emailVerificationTokenHash: string;
    emailVerificationExpiresAt: Date;
  }): Promise<{ tenantId: string; userId: string }> {
    const templateSlug = args.industryTemplateSlug ?? 'cybersecurity';
    return this.prisma.$transaction(async (tx) => {
      // Verify the template exists before any writes so we fail fast
      // (and cleanly — the tx rolls back). The signup DTO is plain
      // string validation; the FK on `tenants.industry_template_slug`
      // would also catch this, but raising a typed error makes the
      // failure mode obvious to the controller.
      const tpl = await tx.industryTemplate.findUnique({
        where: { slug: templateSlug },
        select: { slug: true },
      });
      if (!tpl) throw new BadRequestException('unknown_industry_template');

      const tenant = await tx.tenant.create({
        data: { name: args.tenantName, industryTemplateSlug: templateSlug },
        select: { id: true },
      });

      // Clone the template's categories into per-tenant rows. Empty for
      // the 'blank' template — leaves the tenant with no taxonomy until
      // they add categories via the Categories settings tab. Raw SQL
      // because Prisma doesn't natively express INSERT…SELECT across
      // models in a single statement.
      await tx.$executeRaw`
        INSERT INTO opportunity_categories (tenant_id, slug, name, parent_slug, position)
        SELECT ${tenant.id}::uuid, c.slug, c.name, c.parent_slug, c.position
          FROM industry_template_categories c
         WHERE c.template_slug = ${templateSlug}
      `;

      const user = await tx.user.create({
        data: {
          tenantId: tenant.id,
          email: args.email,
          ...(args.userName !== undefined && args.userName.trim().length > 0
            ? { name: args.userName.trim() }
            : {}),
          passwordHash: args.passwordHash,
          role: 'admin',
          emailVerified: false,
          emailVerificationTokenHash: args.emailVerificationTokenHash,
          emailVerificationExpiresAt: args.emailVerificationExpiresAt,
        },
        select: { id: true },
      });
      return { tenantId: tenant.id, userId: user.id };
    });
  }

  /**
   * Look up pending email-verification candidates. Mirrors findFreshMagicLinks:
   * caller argon2-verifies the URL token against each row to find the match.
   *
   * Cap at 200 — verifications shouldn't accumulate (default TTL is 24h and
   * the partial index on (email_verification_expires_at) makes this fast).
   */
  async findPendingEmailVerifications(limit = 200): Promise<
    Array<{ id: string; tenantId: string; email: string; tokenHash: string }>
  > {
    type Row = { id: string; tenant_id: string; email: string; email_verification_token_hash: string };
    const rows = await this.prisma.$queryRaw<Row[]>`SELECT id, tenant_id, email, email_verification_token_hash
        FROM users
       WHERE email_verified = FALSE
         AND email_verification_token_hash IS NOT NULL
         AND email_verification_expires_at > now()
       ORDER BY email_verification_expires_at DESC
       LIMIT ${limit}`;
    return rows.map((r) => ({
      id: r.id,
      tenantId: r.tenant_id,
      email: r.email,
      tokenHash: r.email_verification_token_hash,
    }));
  }

  /**
   * Mark a user's email as verified after a successful token argon2-check.
   * Runs as superuser (no tenant ctx yet — the JWT hasn't been issued).
   */
  async markEmailVerified(userId: string): Promise<void> {
    await this.prisma.$executeRaw`UPDATE users
        SET email_verified = TRUE,
            email_verification_token_hash = NULL,
            email_verification_expires_at = NULL
      WHERE id = ${userId}::uuid`;
  }

  /**
   * Returns active (unexpired, unconsumed) password-reset candidates so the
   * caller can argon2-verify the URL token against each. Same shape and
   * reasoning as findFreshMagicLinks.
   */
  async findFreshPasswordResets(limit = 50): Promise<
    Array<{ id: string; tenantId: string; userId: string; tokenHash: string }>
  > {
    type Row = { id: string; tenant_id: string; user_id: string; token_hash: string };
    const rows = await this.prisma.$queryRaw<Row[]>`SELECT id, tenant_id, user_id, token_hash
        FROM password_resets
       WHERE expires_at > now() AND consumed_at IS NULL
       ORDER BY created_at DESC
       LIMIT ${limit}`;
    return rows.map((r) => ({
      id: r.id,
      tenantId: r.tenant_id,
      userId: r.user_id,
      tokenHash: r.token_hash,
    }));
  }

  /**
   * Returns the N most recent unexpired, unconsumed magic links, so the caller
   * can argon2-verify the provided token against each candidate.
   *
   * Why N=50: magic-link windows are short (default 15 min) and the table is
   * indexed on (expires_at, consumed_at); in practice only a handful of rows
   * match at any moment. This bound stops pathological cases.
   */
  async findFreshMagicLinks(limit = 50): Promise<
    Array<{ id: string; tenantId: string; userId: string; tokenHash: string }>
  > {
    type Row = { id: string; tenant_id: string; user_id: string; token_hash: string };
    const rows = await this.prisma.$queryRaw<Row[]>`SELECT id, tenant_id, user_id, token_hash
        FROM magic_links
       WHERE expires_at > now() AND consumed_at IS NULL
       ORDER BY created_at DESC
       LIMIT ${limit}`;
    return rows.map((r: Row) => ({
      id: r.id,
      tenantId: r.tenant_id,
      userId: r.user_id,
      tokenHash: r.token_hash,
    }));
  }

  /**
   * Pending invites that have not been accepted, revoked, or expired.
   * Same shape as findFreshMagicLinks: caller argon2-verifies the token
   * against each row to discover the tenant.
   */
  async findOpenInvites(limit = 100): Promise<
    Array<{ id: string; tenantId: string; email: string; role: string; tokenHash: string }>
  > {
    type Row = {
      id: string;
      tenant_id: string;
      email: string;
      role: string;
      token_hash: string;
    };
    const rows = await this.prisma.$queryRaw<Row[]>`SELECT id, tenant_id, email, role, token_hash
        FROM invites
       WHERE expires_at > now() AND accepted_at IS NULL AND revoked_at IS NULL
       ORDER BY created_at DESC
       LIMIT ${limit}`;
    return rows.map((r: Row) => ({
      id: r.id,
      tenantId: r.tenant_id,
      email: r.email,
      role: r.role,
      tokenHash: r.token_hash,
    }));
  }

  /**
   * Cross-tenant pull of engagement_files due for an extraction
   * retry. The retry sweeper has no tenant scope (it runs on a
   * timer, not a request), so we look across the whole platform and
   * dispatch each row's re-kickoff via the tenant-scoped path.
   * Capped at 50 rows per sweep so a backed-up queue can't pin the
   * cron tick.
   */
  async findDueExtractionRetries(limit = 50): Promise<
    Array<{ id: string; tenantId: string; attempts: number }>
  > {
    type Row = { id: string; tenant_id: string; extraction_attempts: number };
    const rows = await this.prisma.$queryRaw<Row[]>`SELECT id, tenant_id, extraction_attempts
        FROM engagement_files
       WHERE extraction_status = 'retry_queued'
         AND extraction_retry_at <= now()
       ORDER BY extraction_retry_at ASC
       LIMIT ${limit}`;
    return rows.map((r: Row) => ({
      id: r.id,
      tenantId: r.tenant_id,
      attempts: r.extraction_attempts,
    }));
  }

  /**
   * Cross-tenant pull of site_enumerations due for a retry. Same shape
   * as findDueExtractionRetries — the retry sweeper has no tenant
   * scope, so it looks across the platform and dispatches each row's
   * re-run via the tenant-scoped path inside SiteEnumService.
   * Capped at 50 rows per sweep so a backed-up queue can't pin the
   * cron tick.
   */
  async findDueSiteEnumerationRetries(limit = 50): Promise<
    Array<{ id: string; tenantId: string; attempts: number }>
  > {
    type Row = { id: string; tenant_id: string; attempts: number };
    const rows = await this.prisma.$queryRaw<Row[]>`SELECT id, tenant_id, attempts
        FROM site_enumerations
       WHERE status = 'retry_queued'
         AND retry_at <= now()
       ORDER BY retry_at ASC
       LIMIT ${limit}`;
    return rows.map((r: Row) => ({
      id: r.id,
      tenantId: r.tenant_id,
      attempts: r.attempts,
    }));
  }

  /**
   * Delete LLM email-extraction cache rows older than `days` days, across
   * all tenants. Runs as the system role because the sweep has no tenant
   * scope (it's a timer, not a request). The cache is a convenience layer
   * over the preview LLM call — purging stale rows just forces a fresh
   * extraction next time that email is opened.
   *
   * Returns the number of rows deleted (for logging).
   */
  async purgeStaleEmailExtractions(days = 30): Promise<number> {
    // `${days}::int`: Prisma binds the JS number as bigint, but Postgres
    // make_interval(days => …) only accepts int4 — without the cast it
    // raises 42883 ("function does not exist") and the purge silently fails.
    const deleted = await this.prisma.$executeRaw`
      DELETE FROM email_extraction_cache
       WHERE created_at < now() - make_interval(days => ${days}::int)`;
    return deleted;
  }

  /** Tenant name for the invite-preview page; needs no tenant scope. */
  async findTenantName(tenantId: string): Promise<string | null> {
    const rows = await this.prisma.$queryRaw<Array<{ name: string }>>`
      SELECT name FROM tenants WHERE id = ${tenantId}::uuid LIMIT 1`;
    return rows[0]?.name ?? null;
  }

  /**
   * All tenant ids, for cross-tenant scheduled sweeps (e.g. the nightly
   * audit-chain seal). No tenant scope — the sweeper runs on a timer, not a
   * request, and fans out to the tenant-scoped path (TenantDb) per id.
   * Ordered by created_at so the sweep order is deterministic. Unbounded by
   * design: every tenant must be sealed; the caller paces the per-tenant work.
   */
  async findAllTenantIds(): Promise<string[]> {
    const rows = await this.prisma.$queryRaw<Array<{ id: string }>>`
      SELECT id FROM tenants ORDER BY created_at ASC`;
    return rows.map((r) => r.id);
  }

  /**
   * Returns active (unexpired, unrevoked) gathering tokens. The plaintext
   * token coming in over `/g/:token` doesn't reveal a tenant, so token
   * resolution scans candidates and verifies each via argon2.
   *
   * `LIMIT 200` is comfortably above any realistic in-flight count for a
   * tenant; a higher value here mostly trades RAM for fewer pages.
   */
  async findActiveGatheringTokens(limit = 200): Promise<
    Array<{
      id: string;
      tenantId: string;
      engagementId: string;
      tokenHash: string;
      boundFingerprintHash: string | null;
      accessCount: number;
    }>
  > {
    type Row = {
      id: string;
      tenant_id: string;
      engagement_id: string;
      token_hash: string;
      bound_fingerprint_hash: string | null;
      access_count: number;
    };
    const rows = await this.prisma.$queryRaw<Row[]>`SELECT id, tenant_id, engagement_id, token_hash,
                                                            bound_fingerprint_hash, access_count
        FROM gathering_tokens
       WHERE expires_at > now() AND revoked_at IS NULL
       ORDER BY created_at DESC
       LIMIT ${limit}`;
    return rows.map((r: Row) => ({
      id: r.id,
      tenantId: r.tenant_id,
      engagementId: r.engagement_id,
      tokenHash: r.token_hash,
      boundFingerprintHash: r.bound_fingerprint_hash,
      accessCount: r.access_count,
    }));
  }
}
